[[Musl]]
arch = "x86_64"
git-tree-sha1 = "fe1d08956282c68c349bb5e203b3861a752947c7"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "33f5c98fbac161fc8c1af8e238a4296d06319b2ec42965cd5df318ae12c79d1f"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.1.22+0/Musl.v1.1.22.x86_64-linux-musl.tar.gz"
[[Musl]]
arch = "i686"
git-tree-sha1 = "6eec2cf3da2fd6c7a2d84ce5151405b11d4ba1da"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "7135c57cdf27b23488a0517b9095ef303b09ed8de4bb916e8c7f3705edadb879"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.1.22+0/Musl.v1.1.22.i686-linux-musl.tar.gz"
[[Musl]]
arch = "aarch64"
git-tree-sha1 = "183c51122ef47e0459dcd1477bca732b02652e6d"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "0dab19020c3540c6d7c212863f2110f51bad69ed32d04d33030953586218df9f"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.1.22+0/Musl.v1.1.22.aarch64-linux-musl.tar.gz"
[[Musl]]
arch = "armv7l"
git-tree-sha1 = "98c8f9fdb7adcbe41d26e38ac06f3523008d8d9f"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "6d297abc8048c53dba1a543fbfe2f61ad6d61f78a228cdd46a50a210d2882ece"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.1.22+0/Musl.v1.1.22.arm-linux-musleabihf.tar.gz"
