[[Musl]]
arch = "aarch64"
git-tree-sha1 = "cd148f1ac24719c61715bf63189905b63ece115a"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "ed334e7267e3e25127d606ff440a5fcf6f1ba47fcecab74b8f5032e8ff433228"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.2.2+0/Musl.v1.2.2.aarch64-linux-musl.tar.gz"
[[Musl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e78d5aeff99dc018a952f9a3f4096db612957f20"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "a12fc9befc510717133341ff941b2a0bfe1bdf0f0e81c16eb7241511f8f78355"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.2.2+0/Musl.v1.2.2.armv6l-linux-musleabihf.tar.gz"
[[Musl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aa09e73cff929007a8941a27ba8c750099e4478c"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "5d96fcd6b8707bc17acf37b3649f6e7830fe616ef3bc09c25819463c7575d484"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.2.2+0/Musl.v1.2.2.armv7l-linux-musleabihf.tar.gz"
[[Musl]]
arch = "i686"
git-tree-sha1 = "920d00a8b1f2b5c9a8c27ee907a4e5d1f7742e9b"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "3f4cbf769efaf512e64170f31ef094db2762d7ea10118899b890140534119b62"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.2.2+0/Musl.v1.2.2.i686-linux-musl.tar.gz"
[[Musl]]
arch = "x86_64"
git-tree-sha1 = "53a70f4cd76584c11ba4161960fcfd0336a02f94"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "bac2021eb400e8a6d1bf61efa9b0b4e1c5bab1c97791e9154dc9bcd5fa7c61f7"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.2.2+0/Musl.v1.2.2.x86_64-linux-musl.tar.gz"
