[[Musl]]
arch = "x86_64"
git-tree-sha1 = "494ad5aec7270e842f2dc63ce7dc01c19b4433f5"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "489c790397a03165892dbbaff1ba371f44e67fb30a5ed7ff6246481a418efcef"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.1.22+0/Musl.v1.1.22.x86_64-linux-musl.tar.gz"
[[Musl]]
arch = "i686"
git-tree-sha1 = "4b031709ac87d5078b50bee6f6c979b7976690d7"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "539eb83986c90c197bdbd73730dcefc3b1a9f8c1bf4b0114dbf44d7ea957806c"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.1.22+0/Musl.v1.1.22.i686-linux-musl.tar.gz"
[[Musl]]
arch = "aarch64"
git-tree-sha1 = "14408d4aec9b59124e0c6d3ca940271fdc647ab9"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "e43013ae682d21a3f8a2cdf580916d9976e40f6b4b0dbc7225e5541edbebbd43"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.1.22+0/Musl.v1.1.22.aarch64-linux-musl.tar.gz"
[[Musl]]
arch = "armv7l"
git-tree-sha1 = "5529c2e89a2fa5730ad01d0fc12f742d61838a7e"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "a0b6519e750dc143d82e3d63cd2b6189e9ad5d6cd7bd058d122b6c86b77f7b3e"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.1.22+0/Musl.v1.1.22.arm-linux-musleabihf.tar.gz"
