[[Musl]]
arch = "aarch64"
git-tree-sha1 = "6d60f8cca596f73017889890cf62a9e95775c351"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "2287eb7fdc4db57d08502cff5e114be3d28d7f4740904d20cef972af45aacc4a"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.1.24+0/Musl.v1.1.24.aarch64-linux-musl.tar.gz"
[[Musl]]
arch = "armv7l"
git-tree-sha1 = "8137e093b9c5cd62636960981f408393aa4a4fc1"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "5245f53fb02ef44bfc11b8586bb9c3585c86274e4894d5cf88d66336eadb1ca1"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.1.24+0/Musl.v1.1.24.armv7l-linux-musleabihf.tar.gz"
[[Musl]]
arch = "i686"
git-tree-sha1 = "ff795c54fd1e9163129daa209d388d85cfea7cb0"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "da049648f23a05753f4d2c8392ed7e381330b136bfaf94e6a33ce57a10924c0b"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.1.24+0/Musl.v1.1.24.i686-linux-musl.tar.gz"
[[Musl]]
arch = "x86_64"
git-tree-sha1 = "5aabfc5da18fa3a6af4d3904d5e8e9998e250a11"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "82042a189d2b116d60ebda1b39eb358a0e80e39e9fce2fc6a94accc5e507dd9d"
    url = "https://github.com/JuliaBinaryWrappers/Musl_jll.jl/releases/download/Musl-v1.1.24+0/Musl.v1.1.24.x86_64-linux-musl.tar.gz"
