# Autogenerated wrapper script for Musl_jll for armv7l-linux-musleabihf
export libc

JLLWrappers.@generate_wrapper_header("Musl")
JLLWrappers.@declare_library_product(libc, "libc.musl-armhf.so.1")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libc,
        "lib/ld-musl-armhf.so.1",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
