# Autogenerated wrapper script for Musl_jll for x86_64-linux-musl
export libc

JLLWrappers.@generate_wrapper_header("Musl")
JLLWrappers.@declare_library_product(libc, "libc.musl-.so.1")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libc,
        "lib/ld-musl-x86_64.so.1",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
